# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-12 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('username', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('action_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('mem_free', models.CharField(blank=True, max_length=50, null=True)),
                ('mem_used', models.CharField(blank=True, max_length=50, null=True)),
                ('mem_total', models.CharField(blank=True, max_length=50, null=True)),
                ('up_day', models.CharField(blank=True, max_length=50, null=True)),
                ('up_hour', models.CharField(blank=True, max_length=50, null=True)),
                ('up_minute', models.CharField(blank=True, max_length=50, null=True)),
                ('up_free', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_count', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_pcount', models.CharField(blank=True, max_length=50, null=True)),
                ('disk1_used', models.CharField(blank=True, max_length=50, null=True)),
                ('disk1_total', models.CharField(blank=True, max_length=50, null=True)),
                ('disk1_percent', models.CharField(blank=True, max_length=50, null=True)),
                ('disk1_name', models.CharField(blank=True, max_length=50, null=True)),
                ('disk1_free', models.CharField(blank=True, max_length=50, null=True)),
                ('net_port1', models.CharField(blank=True, max_length=50, null=True)),
                ('net_port1_rec', models.CharField(blank=True, max_length=50, null=True)),
                ('net_port1_send', models.CharField(blank=True, max_length=50, null=True)),
                ('net_port2', models.CharField(blank=True, max_length=50, null=True)),
                ('net_port2_rec', models.CharField(blank=True, max_length=50, null=True)),
                ('net_port2_send', models.CharField(blank=True, max_length=50, null=True)),
                ('lovg_1', models.CharField(blank=True, max_length=50, null=True)),
                ('lavg_5', models.CharField(blank=True, max_length=50, null=True)),
                ('lavg_15', models.CharField(blank=True, max_length=50, null=True)),
                ('lavg_last_pid', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
