# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-16 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='diskstat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk1', models.CharField(blank=True, max_length=50, null=True)),
                ('disk2', models.CharField(blank=True, max_length=50, null=True)),
                ('disk3', models.CharField(blank=True, max_length=50, null=True)),
                ('disk4', models.CharField(blank=True, max_length=50, null=True)),
                ('disk5', models.CharField(blank=True, max_length=50, null=True)),
                ('disk6', models.CharField(blank=True, max_length=50, null=True)),
                ('disk7', models.CharField(blank=True, max_length=50, null=True)),
                ('disk8', models.CharField(blank=True, max_length=50, null=True)),
                ('disk9', models.CharField(blank=True, max_length=50, null=True)),
                ('disk10', models.CharField(blank=True, max_length=50, null=True)),
                ('disk11', models.CharField(blank=True, max_length=50, null=True)),
                ('disk12', models.CharField(blank=True, max_length=50, null=True)),
                ('disk13', models.CharField(blank=True, max_length=50, null=True)),
                ('disk14', models.CharField(blank=True, max_length=50, null=True)),
                ('disk15', models.CharField(blank=True, max_length=50, null=True)),
                ('disk16', models.CharField(blank=True, max_length=50, null=True)),
                ('disk17', models.CharField(blank=True, max_length=50, null=True)),
                ('disk18', models.CharField(blank=True, max_length=50, null=True)),
                ('disk19', models.CharField(blank=True, max_length=50, null=True)),
                ('disk20', models.CharField(blank=True, max_length=50, null=True)),
                ('disk21', models.CharField(blank=True, max_length=50, null=True)),
                ('disk22', models.CharField(blank=True, max_length=50, null=True)),
                ('disk23', models.CharField(blank=True, max_length=50, null=True)),
                ('disk24', models.CharField(blank=True, max_length=50, null=True)),
                ('disk25', models.CharField(blank=True, max_length=50, null=True)),
                ('disk26', models.CharField(blank=True, max_length=50, null=True)),
                ('disk27', models.CharField(blank=True, max_length=50, null=True)),
                ('disk28', models.CharField(blank=True, max_length=50, null=True)),
                ('disk29', models.CharField(blank=True, max_length=50, null=True)),
                ('disk30', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'diskstat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='netstat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net1', models.CharField(blank=True, max_length=50, null=True)),
                ('net2', models.CharField(blank=True, max_length=50, null=True)),
                ('net3', models.CharField(blank=True, max_length=50, null=True)),
                ('net4', models.CharField(blank=True, max_length=50, null=True)),
                ('net5', models.CharField(blank=True, max_length=50, null=True)),
                ('net6', models.CharField(blank=True, max_length=50, null=True)),
                ('net7', models.CharField(blank=True, max_length=50, null=True)),
                ('net8', models.CharField(blank=True, max_length=50, null=True)),
                ('net9', models.CharField(blank=True, max_length=50, null=True)),
                ('net10', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'netstat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='sysstat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loadaverage', models.CharField(blank=True, max_length=50, null=True)),
                ('uptime', models.CharField(blank=True, max_length=50, null=True)),
                ('totaltask', models.CharField(blank=True, max_length=50, null=True)),
                ('running', models.CharField(blank=True, max_length=50, null=True)),
                ('sleeping', models.CharField(blank=True, max_length=50, null=True)),
                ('stopped', models.CharField(blank=True, max_length=50, null=True)),
                ('zombie', models.CharField(blank=True, max_length=50, null=True)),
                ('cpuus', models.CharField(blank=True, max_length=50, null=True)),
                ('cpusy', models.CharField(blank=True, max_length=50, null=True)),
                ('cpyni', models.CharField(blank=True, max_length=50, null=True)),
                ('cpuid', models.CharField(blank=True, max_length=50, null=True)),
                ('cpuwa', models.CharField(blank=True, max_length=50, null=True)),
                ('cpuhi', models.CharField(blank=True, max_length=50, null=True)),
                ('cpusi', models.CharField(blank=True, max_length=50, null=True)),
                ('cpust', models.CharField(blank=True, max_length=50, null=True)),
                ('memtotal', models.CharField(blank=True, max_length=50, null=True)),
                ('memfree', models.CharField(blank=True, max_length=50, null=True)),
                ('memused', models.CharField(blank=True, max_length=50, null=True)),
                ('memcache', models.CharField(blank=True, max_length=50, null=True)),
                ('swaptotal', models.CharField(blank=True, max_length=50, null=True)),
                ('swapfree', models.CharField(blank=True, max_length=50, null=True)),
                ('swapused', models.CharField(blank=True, max_length=50, null=True)),
                ('swapcache', models.CharField(blank=True, max_length=50, null=True)),
                ('hostname', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_pcount', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_lcount', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'sysstat',
                'managed': False,
            },
        ),
    ]
